name: Run Automation Tests on Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
    - name: ⬇️ Checkout Code
      uses: actions/checkout@v3

    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 📦 Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 🎭 Install Playwright Browsers
      run: |
        python -m playwright install --with-deps

    - name: 🧪 Run Tests (Headless Mode)
      run: |
        pytest --html=reports/report.html --self-contained-html

    - name: 📤 Upload HTML Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: html-report
        path: reports/report.html
